name: Android CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read
  actions: read
  id-token: write
  pull-requests: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Show Gradle & Kotlin versions
        run: ./gradlew -version

      - name: Build (Assemble Debug)
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon
        env:
          CI: true

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon
        env:
          CI: true

      - name: Lint (Optional, ignore failure)
        run: |
          ./gradlew lintDebug || echo "Lint failed (non-blocking)"

      - name: Detekt (Optional, ignore failure)
        run: |
          if [ -f detekt.yml ]; then ./gradlew detekt || echo "Detekt failed (non-blocking)"; fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
          retention-days: 14

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/tests
            **/build/reports/lint-results*.html
            **/build/reports/detekt
          if-no-files-found: ignore
          retention-days: 14

      - name: Cache Gradle Home (additional)
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.gradle/caches
          key: gradle-home-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

  # Gelecekte ayrılabilir: instrumentation, benchmark vb.

